export const courses = () => ([
    {
        id: 1,
        title: 'Python for Everybody Specialization',
        thumb: '/assets/3.jpg',
        author: 'Author 2',
        description: 'Learn to Program and Analyze Data with Python. Develop programs to gather, clean, analyze, and visualize data.',
        price: 19,
        promote: 5,
        tag: "Best seller",
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 2,
        title: 'Course 1 hej hjh jj hjh jh jhj hj hh j hj hj hj hj hj h jh jh jhj hj hj hj hj hj hj hj hj h jh jh jh j hj hj hj hjh jh ',
        thumb: '/assets/1.jpg',
        author: 'Author 1',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 3,
        title: 'Course 2',
        thumb: '/assets/2.jpg',
        author: 'Author 2',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 4,
        title: 'Course 1',
        thumb: '/assets/1.jpg',
        author: 'Author 1',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 5,
        title: 'Course 2',
        thumb: '/assets/2.jpg',
        author: 'Author 2',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 6,
        title: 'Course 1',
        thumb: '/assets/1.jpg',
        author: 'Author 1',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 7,
        title: 'Python for Everybody Specialization',
        thumb: '/assets/3.jpg',
        author: 'Author 2',
        description: 'Learn to Program and Analyze Data with Python. Develop programs to gather, clean, analyze, and visualize data.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 8,
        title: 'Course 1 hej hjh jj hjh jh jhj hj hh j hj hj hj hj hj h jh jh jhj hj hj hj hj hj hj hj hj h jh jh jh j hj hj hj hjh jh ',
        thumb: '/assets/1.jpg',
        author: 'Author 1',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 9,
        title: 'Course 2',
        thumb: '/assets/2.jpg',
        author: 'Author 2',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 10,
        title: 'Course 1',
        thumb: '/assets/1.jpg',
        author: 'Author 1',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 11,
        title: 'Course 2',
        thumb: '/assets/2.jpg',
        author: 'Author 2',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        id: 12,
        title: 'Course 1',
        thumb: '/assets/1.jpg',
        author: 'Author 1',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
]);

export const empty_course = {
    id: 0,
    title: 'Course 1',
    thumb: '/assets/1.jpg',
    author: 'Author 1',
    description: 'Here is a short description for this course. Blab blab blab blab.',
    price: 19,
    rating: 3,
    num_rating: 100,
    num_enrolled: 100,
    language: ['Eng'],
    categories_tree: ['Sample'],
};