export const courses = () => ([
    {
        title: 'Python for Everybody Specialization',
        thumb: 'assets/3.jpg',
        author: 'Author 2',
        description: 'Learn to Program and Analyze Data with Python. Develop programs to gather, clean, analyze, and visualize data.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        title: 'Course 1 hej hjh jj hjh jh jhj hj hh j hj hj hj hj hj h jh jh jhj hj hj hj hj hj hj hj hj h jh jh jh j hj hj hj hjh jh ',
        thumb: 'assets/1.jpg',
        author: 'Author 1',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        title: 'Course 2',
        thumb: 'assets/2.jpg',
        author: 'Author 2',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        title: 'Course 1',
        thumb: 'assets/1.jpg',
        author: 'Author 1',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        title: 'Course 2',
        thumb: 'assets/2.jpg',
        author: 'Author 2',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
    {
        title: 'Course 1',
        thumb: 'assets/1.jpg',
        author: 'Author 1',
        description: 'Here is a short description for this course. Blab blab blab blab.',
        price: 19,
        rating: 3,
        num_rating: 100,
        num_enrolled: 100,
        language: ['Eng', 'Vi', 'Jp'],
        categories_tree: ['Computer Science', 'Software Development'],
    },
]);