module.exports = [{
    'Description': "Hi, I'm Jonas! I have been identified as one of Udemy's Top Instructors and all my premium courses have earned the best-selling status for outstanding performance and student satisfaction.I'm a full-stack web developer and designer with a passion for building beautiful things from scratch. I've been building websites and apps since 2010 and also have a Master's degree in Engineering.I discovered my passion for teaching and helping others by sharing all I knew when I\xa0was in college, and that passion brought me to Udemy in 2015.Here, in all my courses, what students love the most is that I take the time to explain every concept in a way that everyone can easily understand.So, do you want to learn how to build awesome websites with modern HTML\xa0and CSS?Looking for a complete JavaScript course that takes you from zero to an advanced developer?Or maybe you want to build modern and fast back-end applications with Node.js?Then don't waste your time with random tutorials or incomplete youtube videos. All my courses are easy-to-follow, all-in-one packages that will take your skills to the next level.These courses are exactly the courses I wish I had when I was first getting into web development!So see for yourself, enroll in one of my courses (or all of them :D) and join 1,000,000+ happy students today.",
    'User_Id': 2
},
{
    'Description': ' Lawrence Turton works as a web developer & graphic designer specialising in HTML, CSS, jQuery, UI & UX design. He has previously worked with Fifteendesign producing websites, iPhone and Android apps and started his own agency in 2010 called Elite Web Design. During that time Lawrence has established a wide range of clients from blue chip companies to large corporations. From a young age he was an online instructor and started to work with two of the leading online training specialists Cartoonsmart and Envato. Lawrence always created projects involving designs in Photoshop and bringing his creations to life by coding them with web technologies. This gives him a unique perspective into real world projects from start to finish and a wealth of information for new comers to the web industry. ',
    'User_Id': 15
},
{
    'Description': 'Sahand Ghavidel holds degrees in Mathematics, Electrical, and Computer Science, and earned a doctoral degree from Faculty of Engineering and IT, University of Technology Sydney. Sahand has researched for more than 10 years about artificial algorithms and\xa0 optimization. He has won several awards for his outstanding research and has published more than 40 ISI journals and attended to many international conferences. The number of people using and citing Sahand\'s publications is significantly high which is more than 1600 citations, according to google scholar (April, 2021). He was also awarded the outstanding reviewer in the international journal called "International Journal of Electrical Power & Energy Systems" with CiteScore of 5.79 in recognition of his contributions added to the quality of the journal. Sahand has more than 15 years of programming experience. The first programming language he learned was visual basic when he was just 12 years old. Since then, he has made hundreds of websites, and apps with different programming languages like JavaScript and Python. ',
    'User_Id': 28
},
{
    'Description': 'A highly skilled professional, Brad Hussey is a passionate and experienced freelancing\xa0web designer, developer, blogger and digital entrepreneur. Hailing from North Of The Wall (Yellowknife, Canada), Brad made the trek to the Wet Coast (Vancouver, Canada) to educate and equip himself with the necessary skills to become a spearhead in his trade of solving problems on the web, crafting design solutions, and speaking in code.\xa0 Brad\'s determination and love for what he does has landed him in some pretty interesting places with some neat people. He\'s had the privilege of working with, and providing solutions for, numerous businesses, big & small, across the Americas.\xa0 Brad builds custom websites, and provides design solutions for a wide-array of clientele at his company, Brightside Studios. He regularly blogs about passive income, living your life to the fullest, and provides premium quality web design tutorials and courses for tens of thousands of amazing people desiring to master the craft.\xa0 500,000+ Students Don\'t Lie\xa0 Join Brad and adventure into his world of web design, web development, and speaking in code. You won\'t regret it!\xa0 What are people saying about Brad?\xa0 "[Brad is] the BEST coding instructor on the planet. Brad has a passion for teaching and he does it with joy. He pours his heart into his lessons and makes you feel at ease. It\'s just like having your best buddy having a chat with you - only this time, you are learning valuable skills. He\'s the type of guy who is passionate about transforming people\'s lives through his lessons. He\'s not after the money. He truly wants you to succeed. Three hearty cheers to Brad - the best coding instructor on planet Earth."— Cicero, Brad\'s student"...These videos are well created, concise, fast-paced, easy to follow, and just funny enough to keep you chuckling as you\'re slamming out lines of code. I\'ve taken 3 courses from this instructor. Whenever I have questions he is right there with a simple solution or a helpful suggestion to keep me going forward with the course work."— Brennan, Brad\'s student"...Brad is amazing and I honestly think he\'s the best tutor of all the courses I have taken on Udemy. Will definitely be following him in the future. Thanks Brad!"— Brad\'s student"...Brad has an infectious enthusiasm, a great eye for detail, and expert-level knowledge of the material."— Brad\'s student',
    'User_Id': 35
},
{
    'Description': "\xa0 R-Tutorials is your provider of choice when it comes to\xa0analytics training courses! Try it out – our 100,000+ students love it.\xa0 \xa0 \xa0 \xa0 \xa0 We focus on\xa0Data Science tutorials. Offering several\xa0R courses for every skill level, we are among Udemy's top\xa0R training provider. On top of that courses on Tableau, Excel and a Data Science career guide are available.\xa0 \xa0 \xa0 \xa0 All of our courses contain exercises to give you the opportunity to try out the material on your own. You will also get downloadable script pdfs to recap the lessons.\xa0 \xa0 \xa0 \xa0 \xa0 The courses are\xa0taught by our main instructor Martin – trained biostatistician and enthusiastic data scientist /\xa0R user.\xa0 \xa0 \xa0 \xa0 \xa0 Should you have any questions, you are invited to check out our website, you can open a discussion in the course or you can simply drop us a pm.\xa0 \xa0 \xa0 \xa0 \xa0 We are here\xa0to help you boost your career with\xa0analytics training – Just learn and enjoy.\xa0 ",
    'User_Id': 48
},
{
    'Description': 'I am a coder, manager, educator and a gamer. I love data and analytics. In my day job, I work with database technologies including SQL , Big Data and Tableau. I am passionate about technologies and love coding and managing teams. In my spare time I like to teach Big Data analytics, Databases, Programming etc. I am currently working on certain machine learning and Data Science projects and love to explore more in the Statistics field.',
    'User_Id': 61
},
{
    'Description': "I'm the founder of LogikBot. I've worked at Microsoft and Uber. I helped design courses for Microsoft's Data Science Certifications. If you're interested in machine learning, I can help. I've worked with databases for over two decades. I've worked for or consulted with over 50 different companies as a full time employee or consultant. Fortune 500 as well as several small to mid-size companies. Some include: Georgia Pacific, SunTrust, Reed Construction Data, Building Systems Design, NetCertainty, The Home Shopping Network, SwingVote, Atlanta Gas and Light and Northrup Grumman.\xa0 Over the last five years I've transitioned to the exciting world of applied machine learning.\xa0 I'm excited to show you what I've learned and help you move into one of the single most important fields in this space. Experience, education and passion\xa0 I learn something almost every day. I work with insanely smart people. I'm a voracious learner of all things SQL Server and I'm passionate about sharing what I've learned. My area of concentration is performance tuning. SQL Server is like an exotic sports car, it will run just fine in anyone's hands but put it in the hands of skilled tuner and it will perform like a race car.\xa0 Certifications \xa0 Certifications are like college degrees, they are a great starting points to begin learning. I'm a Microsoft Certified Database Administrator (MCDBA), Microsoft Certified System Engineer (MCSE) and Microsoft Certified Trainer (MCT).\xa0 Personal \xa0 Born in Ohio, raised and educated in Pennsylvania, I currently reside in Atlanta with my wife and two children. \xa0 \xa0 ",
    'User_Id': 74
},
{
    'Description': 'Dr. Charles Redmond is a professor in the Tom Ridge School of Intelligence Studies and Information Science at Mercyhurst University. He has been a member of the Department of Mathematics and Computer Systems at Mercyhurst for 21 years and has recently completed a term as chair of the department. Dr. Redmond received his PhD in mathematics from Lehigh University in 1993 and has published in the Annals of Applied Probability, the Journal of Stochastic Processes and Their Applications, Mathematics Magazine, the College Mathematics Journal, and Mathematics Teacher. In his spare time he enjoys making music and computer generated art, reading, and owning a Clumber Spaniel.',
    'User_Id': 87
},
{
    'Description': 'Founder at NXTGEN A.I Academy.NxtGen A.I Academy stands for both Automate Intelligently and Artificial Intelligence !I’m a data science trainer, automation architect, scrum master and mentor with over 11+ years of experience in the field of Automation Testing, Quality Assurance and Data Science (ML\\DL)Worked at Tata Consultancy Services and Cognizant Technology Solutions as Automation Architect in Belgium and Kingdom of Saudi Arabia.Presently working as full time corporate trainer .',
    'User_Id': 100
},
{
    'Description': "Swift on iOS, a little\xa0Java here and there\xa0and C# for Xamarin. I'll show you how to use them all!When you learn from me you learn in an holistic manner. You learn concepts that are applicable to ALL mobile systems.My aim is to get you qualified mighty fast, with very little hair tearing from frustration.And what does that mean for you?You'll be able to make your own apps to earn passive income. Or you could become a freelance developer which I can honestly say it is the best life in the world. You will have no boss and earn an hourly rate of over $100. You can also take holiday whenever you want.Of course you have to learn how to make good apps first so take my courses now and you will see how easy mobile app development can be!",
    'User_Id': 113
},
{
    'Description': "Hi! I'm Mayuresh Wankhede. I'm a Web/ Android developer\xa0 with a strong focus on pragmatism and simplicity.I have completed my bachelor\xa0 degree in Computer Science Engineering and I am skilled in many development languages including Java, C++ , PHP and to name a few.\nI have been working on a diverse range of different software projects and I enjoy keeping up with time, constantly learning new languages, concepts, and techs.\n",
    'User_Id': 126
},
{
    'Description': "Our dream is to make people independent learners who can learn anything online. Let's create a world where education is not limited to fortunate ones.\xa0We advise our\xa0students to \xa0write a code daily and revisit the same code after a week. You will see yourself growing up as a coder :)",
    'User_Id': 139
},
{
    'Description': 'The App Dojo has helped thousands of students get started developing their own iPhone apps & iMessage sticker packs and distributing those around the world via The App Store. Whether you want to get started selling apps in The App Store, promote a project/product with an app or sticker pack, or supplement your current skillset with valuable mobile development expertise, our tutorials are a great way to get started.',
    'User_Id': 164
},
{
    'Description': "I 'm a 30 year old, self taught web designer and teacher from the North of Ireland!My hobbies include, web design, animation, and beatboxing... but my number one hobby is teaching people new tricks!I've been building websites both personally and professionally for more than 7 years and all of the information contained in my training videos has been learned through trial and error (by yours truly!)I look forward to helping you create a website or blog that you can be proud of!Until Next Time,@MartieDread",
    'User_Id': 177
},
{
    'Description': "\xa0 Carl is the founder of Web Courses and a UX consultant for the United Nations. At Web Courses Carl teaches Web Design and Online Marketing to people from all around the world. He has been designing websites for over 16 years and is passionate about creating usable designs and creative online marketing strategies for WCB and their clients.\xa0 \xa0 Accessibility is a big passion of Carl's and has spoken at UN conferences on Inclusive Business around South East Asia. Recently he has been invited to give Social Media Marketing advise to UNAIDS as part of a new Asia campaign.\xa0 \xa0 When not UX`ing, HTML'ing or teaching there is nothing more Carl likes than a blank canvas on Adobe Photoshop, a tool he has been using since version 3.0!\xa0 ",
    'User_Id': 202
},
{
    'Description': "Christine is a Web Design & SEO Business Coach at Portable Entrepreneur where she directly helps web design and SEO\xa0startups through education, coaching\xa0and services.\xa0Christine has been a web designer for nearly 15 years - 10 of which she has been self-employed. Her work has taken her from working for some start-up dot com companies in the early 2000's to working as a contractor for the Office of the Under Secretary of Defense to her own home office.In her time, she has built 100's of websites and blogs primarily on WordPress and Joomla. Christine has also provided training to individuals and businesses to help\xa0them manage their websites on their own with no knowledge of web coding.",
    'User_Id': 215
},
{
    'Description': 'I am a technology leader, educator, and researcher/practitioner, specializing in cloud and DevOps. I am proudly part of the information systems faculty at a major university, as well as an experienced professional. I have led technology strategy initiatives and teams in such diverse domains as convention and tourism, healthcare, manufacturing, higher education, and government. I am a lifelong student who strongly believes that education is the most powerful way to change the world. I grew up among the snow-capped peaks, industrious spirit, and brightest minds who inhabit the Silicon Slopes in Utah, and I remain inseparably coupled to its people and its spirit.',
    'User_Id': 228
},
{
    'Description': 'Hi, I am Graphic Designer. This is my Logo Design Course, where we will be learning how to create Unique logo design. This is not my full time job and I have client, i work with everyday. Most of my tutorials comes from actual client experience and things i have done on paying jobs. I have made Logos, Advertisements, Posters, Brand Identities, magazines covers etc.',
    'User_Id': 241
},
{
    'Description': " Hardy is a professional concept artist and illustrator working in New Orleans, LA. He has designed and painted hundreds of characters, creatures, machines and scenes for numerous entertainment industry clients. He has had artwork featured in elite digital art annuals such as Exposé. Hardy is also a certified medical illustrator and has a detailed knowledge of human anatomy as it applies to visual art. Hardy has devoted his online teaching career to the goal\xa0of making digital art and all of it's amazing potential\xa0accessible to everyone - even those for whom art school is not feasible.",
    'User_Id': 254
},
{
    'Description': ' Donelli J. DiMaria is a professional artist and teacher living in Santa Fe, NM. He has shown his paintings and drawings through out the US for the past twenty years in numerous galleries and juried/invited arts shows. Over the past four years, he has been in 14 group museum shows and has his work published in the "Artist\'s Magazine", "American Art Collector", and in "The Best of Portrait Painting" (North Light Books). He has been actively teaching the "Reilly" drawing and painting techniques for the past six years. ',
    'User_Id': 275
},
{
    'Description': ' I started Elevated SEO and Web Design while I was working a night job downtown. With a 5-year-old boy and a 2-year-old baby girl, I knew I had to make a change. I decided to follow my dreams, to make the plunge and to never look back! I am so glad I took this rish because the last 5 years have been amazing! I was recently blessed to marry my beautiful wife, who is one of my biggest supporters. Growing personally, spiritually and in business has taught me so much. The best part is that I enjoy doing something that truly challenges me each and every day. \n Elevated SEO and Web Design currently have a production team making our videos. Our goal is to teach online courses to help others expand their knowledge on the types of services we offer. Our courses include Branding and Money Making classes, taught by experts! We believe in community and helping others and our courses are here to serve and teach. We want to make a difference and help you gain knowledge that will prepare you for greatness! \n See you on the inside...\n A bit about Elevated \n MISSION STATEMENT \n Elevated SEO Believes in helping other people grow by challenging the status quo. We help small business owners by crafting their message and attracting their ideal clients. We match one of our custom online marketing packages to your business to create the perfect brand image. \n VISION STATEMENT \n We help businesses grow through our “Build-Optimize-Manage” approach to online marketing. We always provide clear solutions to business owners and marketing directors. We are a full services web development and online marketing solution for your small business needs! From building branded page websites to advanced web applications, Elevated SEO and Web Design can improve your marketing efforts by leveraging the best practices in business strategy and our highly talented and skilled team of web design professionals. \n Our optimized sites can be custom built to showcase your products and services as well as ensuring your best business practices and workflow procedures are being carried out by your employees in a web-based back office system. \n Our experts in brand identity, search-engine optimization, lead generation, online scheduling, and time and billing management can help you revamp your existing system or design a new one from scratch. \n We want to help you succeed by having an excellent online presence. Our Business is built on a foundation of honesty, integrity and professionalism. Our Approach is to start locally and think globally. ',
    'User_Id': 288
},
{
    'Description': " I am the President and CEO of Logical Conclusions, Inc., a training and consulting company specializing in how to create a Customer Focused, Event-Driven organization. For over three decades I've assisted Business Process Management/Improvement and Re-engineering projects at many major corporations and government agencies.  I've created numerous videos and educational tutorials on how to create the definitive efficient business structure for any organization.  I've also taught thousands of attendees at live business user and technical workshop seminars. Being a prolific guest speaker I've given\xa0 talks at many Business Process/Information Resource conferences such as conducting keynote and featured speeches at: Project Management InstituteUS Universities, many ProjectWorld conferences,GIGA Business Process & Workflow International conferenceWorkflow & Re-Engineering International Association (WARIA) conferences. Enterprise Architecture and Business Process Management IIRM conferences. Also presentations at: International Business Rules ForumNational BPR Enterprise Re-Engineering Conf.International Conf. on Software EngineeringTechnology Transfer Institute Many DCI conferencesShared InsightsGIGAICTIPIT & Business Alignment ForumEDP Auditors Assoc. International Conf.DOE Impact Conf.and many more. I've published many books and articles on Business Improvement and Quality Systems Development. My latest e-book is titled “Strategic Planning using a Customer-Focused, Event-Driven model”. I have been a proud participant in the US Citizen Ambassador Program representing the U.S.A. in China and Russia. I can be reached at: Brian@LogicalConclusionsInc.com\xa0",
    'User_Id': 301
},
{
    'Description': 'Sou Doutora em Design, Mestre em Design Estratégico, Especialista em Expressão Gráfica e Bacharel em Design de Moda.Tenho paixão pelo ensino e, por isto, dediquei dez anos da minha carreira (entre 2007 e 2017) como professora universitária de duas grandes Universidades do Sul do Brasil (Unisinos e Feevale). Ao longo deste período, orientei\xa0mais de 60 projetos de Design com enfoque em\xa0Inovação e avaliei centenas de ideias incríveis.Fui gestora do Centro de Design Feevale, conduzindo o desenvolvimento de de dezenas de projetos para diferentes objetivos e que vão desde produto, moda, gráfico e até território. Coordenei um Bacharelado da Indústria Criativa da Unisinos, implementando novas disciplinas, montando laboratórios e contratando a equipe de professores.Organizei dezenas de Concursos, Exposições e Cursos de Extensão relacionados com o Design e a Indústria Criativa como um todo.Sou gaúcha e amo o Brasil, mas tenho uma inquietação por desbravar o mundo. Hoje eu moro em Lisboa, Portugal. Já morei na Alemanha e em Malta, uma pequena Ilha-país pouco conhecida e que fica localizada entre a África (Tunísia e Líbia) e a Europa (Itália).Se tiver alguma dúvida, me escreve. ;)',
    'User_Id': 314
},
{
    'Description': 'Hallo everyone, I am Mr. Vilas K. Patil received a Master of Design from I.I.T Guwahati and currently a research scholar of A.V.C.O.E Sangamner, and faculty of Mechanical EngineeringDepartment of K.K.Wagh. I.E.E.&R, Nashik. My research area is Design a machine element for various system like Agriculture Product Design, Failure Analysis, Self lubricating Composites and Solid Bearing. I have developed so many agricultural machinery products like internal harvesting unit, pesticide spray unit, plant bowing machine, and provided the design solution for industry.',
    'User_Id': 327
},
{
    'Description': 'Tom Giordano is a 28 year veteran of Philips Healthcare. He retired in 2005 as Vice President of Marketing, where he was responsible for 240 marketing professionals and several billion dollars in product. Through his career, Tom held a wide variety of positions of increasing responsibility at Philips, starting in engineering, progressing to product management, then marketing management and finally senior level business leadership. In 2004, he was awarded the prestigious Presidential Award from Philips for forming a new entrepreneurial business unit that tripled sales in 18 months. Tom played a key role as a course developer and instructor in the management development and executive training efforts with the Philips High Potential Development Center.Following his retirement from Philips, Tom joined the adjunct faculty of the graduate business schools of the University of New Haven in Connecticut and the University of Washington in Seattle.\xa0 He currently holds a positiion as "Executive in Residence" at the University of New Haven and continues to teach there with exceptionally high student reviews.In 2009, while teaching at UW and UNH, he became President of Sectra Healthcare North America for 2 years to lead a very successful turnaround effort.Tom built a very successful internship program between Philips and the University of Washington and served as a mentor there for 15 years.\xa0 He also served as a mentor in the University of Washington mentor program and was featured in the book "Mentoring Moments" by Susan Canfield. Tom serves as chairman of the\xa0 Patient Advisory Council of Saint Vincent\'s Hospital in Bridgeport, CTTom holds executive coaching certifications with both Lore International and Tilt 360.\xa0 \xa0He holds a BS in Electrical Engineering from Drexel University in Philadelphia and a MS degree in Engineering from the University of Florida.',
    'User_Id': 328
},
{
    'Description': '■設立昭和59年6月18日\u3000社団法人設立(通商産業省設立許可)（以下2団体の合併）\u3000社団法人日本情報センター協会\u3000\u3000\u3000（昭和45年6月設立）\u3000\u3000社団法人ソフトウェア産業振興協会\u3000（昭和45年6月設立）平成23年4月1日\u3000一般社団法人へ移行（内閣総理大臣移行認可）■主な事業JISAは、情報サービス産業に関する以下の活動を行っています。１．経営、技術、環境、貿易・投資等に関する調査研究２．品質、生産性、信頼性、セキュリティ等に関する技術開発及び標準化３．取引の高度化及び知的財産の保護４．IT人材の育成及び地域の振興５．多国間(WITSA、ASOCIO等)・2国間の交流・連携及びグローバル化対応６．プライバシーマーク審査７．関係機関等との情報交流・連携及び政府等への意見表明・具申８．活動成果の普及及び刊行物の発行、定期ニュースの発信等関係情報の提供９．地区会等の会員交流活動及び損害・生命保険、401K等の会員向けサービス\xa0 ',
    'User_Id': 329
},
{
    'Description': 'Hi! I\'m Colt. I\'m a developer with a serious love for teaching. I\'ve spent the last few years teaching people to program at 2 different immersive bootcamps where I\'ve helped hundreds of people become web developers and change their lives. My graduates work at companies like Google, Salesforce, and Square.Most recently, I led Galvanize\'s SF\'s 6 month immersive program as Lead Instructor and Curriculum Director. After graduating from my class, 94% of my students went on to receive full-time developer roles. I also worked at Udacity as a Senior Course Developer on the web development team where I got to reach thousands of students daily. I’ve since focused my time on bringing my classroom teaching experience to an online environment. In 2016 I launched my Web Developer Bootcamp course, which has since gone on to become one of the best selling and top rated courses on Udemy. I was also voted Udemy’s Best New Instructor of 2016. I\'ve spent years figuring out the "formula" to teaching technical skills in a classroom environment, and I\'m really excited to finally share my expertise with you. I can confidently say that my online courses are without a doubt the most comprehensive ones on the market. Join me on this crazy adventure!',
    'User_Id': 342
},
{
    'Description': "I'm Angela, I'm a developer with a passion for teaching. I'm the lead instructor at the London App Brewery, London's leading Programming Bootcamp. I've helped hundreds of thousands of students learn to code and change their lives by becoming a developer. I've been invited by companies such as Twitter, Facebook and Google to teach their employees.My first foray into programming was when I was just 12 years old, wanting to build my own Space Invader game. Since then, I've made hundred of websites, apps and games. But most importantly, I realised that my greatest passion is teaching. I spend most of my time researching how to make learning to code fun and make hard concepts easy to understand. I apply everything I discover into my bootcamp courses. In my courses, you'll find lots of geeky humour but also lots of explanations and animations to make sure everything is easy to understand. I'll be there for you every step of the way.",
    'User_Id': 355
},
{
    'Description': "Stephen Grider has been building complex Javascript front ends for top corporations in the San Francisco Bay Area.\xa0 With an innate ability to simplify complex topics, Stephen has been mentoring engineers beginning their careers in software development for years, and has now expanded that experience onto Udemy, authoring the highest rated React course. He\xa0teaches on Udemy to share the knowledge he\xa0has\xa0gained with other software engineers.\xa0 Invest in yourself by learning from Stephen's published courses.",
    'User_Id': 380
},
{
    'Description': "  \t       Hi! I'm Rob. I have a degree in Mathematics from Cambridge University and you might call me a bit of coding geek.  \n  \t       After building websites for friends and family for fun, I soon learned that web development was a very lucrative career choice. I gave up my successful (and sometimes stressful) job as a teacher to work part time and today, couldn't be happier.  \n  \t       I'm passionate about teaching kids to code, so every summer I run Code School in the beautiful city of Cambridge. I also run the popular web hosting and design service, Eco Web Hosting which leaves me free to share my secrets with people like you.  \n You wouldn't believe the freedom that being a web developer offers. Sign up and find out for yourself why so many people are taking and recommending this course.  I genuinely believe it's the best on the market and if you don't agree, I'll happily refund your money.  \n  \t       Sign up to my courses and join me in this amazing adventure today.  ",
    'User_Id': 393
},
{
    'Description': 'My name is Kirill Eremenko and I am super-psyched that you are reading this!Professionally, I am a Data Science management consultant with over five years of experience in finance, retail, transport and other industries. I was trained by the best analytics mentors at Deloitte Australia and today I leverage Big Data to drive business strategy, revamp customer experience and revolutionize existing operational processes.From my courses you will straight away notice how I combine my real-life experience and academic background in Physics and Mathematics to deliver professional step-by-step coaching in the space of Data Science. I am also passionate about public speaking, and regularly present on Big Data at leading Australian universities and industry events.To sum up, I am absolutely and utterly passionate about Data Science and I am looking forward to sharing my passion and knowledge with you!',
    'User_Id': 406
},
{
    'Description': '\xa0 Jose Marcial Portilla has a BS and MS in Mechanical Engineering from Santa Clara University and\xa0years of\xa0experience as a professional instructor and trainer for Data Science and programming. He has publications and patents in various fields such as microfluidics,\xa0materials science, and data science technologies. Over the course of his career he has developed a skill set in analyzing data and he hopes to use his experience in teaching and data science to help other people learn the power of programming the\xa0ability to analyze data, as well as present the data in clear and beautiful visualizations. Currently he works as the Head of Data Science for Pierian Data Inc.\xa0and provides in-person data science and python programming training courses to employees working at top companies, including General Electric, Cigna, The New York Times, Credit Suisse, McKinsey and many more.\xa0Feel free to contact him on LinkedIn for more information on in-person training sessions or group training sessions in Las Vegas, NV.',
    'User_Id': 419
},
{
    'Description': "365 Careers is the #1 best-selling provider of business, finance, and data science courses on Udemy. The company’s courses have been taken by more than 1,500,000 students in 210\xa0countries. People working at world-class firms like Apple, PayPal, and Citibank have completed 365 Careers trainings.\xa0 \xa0\xa0Currently, the 365 focuses on the following topics on Udemy:\xa0 \xa0 \n\n1) Finance – Finance fundamentals, Financial modeling in Excel, Valuation, Accounting, Capital budgeting, Financial statement analysis (FSA), Investment banking (IB), Leveraged buyout (LBO), Financial planning and analysis (FP&A), Corporate budgeting, applying Python for Finance, Tesla valuation case study, CFA, ACCA, and CPA2) Data science – Statistics, Mathematics, Probability, SQL, Python programming, Python for Finance, Business Intelligence, R, Machine Learning, TensorFlow, Tableau, the integration of SQL\xa0and\xa0Tableau, the integration of SQL, Python, Tableau, Power\xa0BI, Credit Risk Modeling, and Credit Analytics, Data literacy, Product Management, Pandas, Numpy, Python Programming, Data Strategy3) Entrepreneurship – Business Strategy, Management and HR Management, Marketing, Decision Making, Negotiation, and Persuasion, Tesla's Strategy and Marketing4) Office productivity – Microsoft Excel, PowerPoint, Microsoft Word, and Microsoft Outlook5) Blockchain for BusinessAll of our courses are: \xa0 - Pre-scripted \xa0 - Hands-on\xa0 \xa0\xa0- Laser-focused\xa0 \xa0- Engaging\xa0 \xa0- Real-life tested\xa0 \xa0 By choosing 365 Careers, you make sure you will learn from proven experts, who have a passion for teaching, and can take you from beginner to pro in the shortest possible amount of time. \xa0 If you want to become a financial analyst, a data scientist, a business analyst, a data analyst, a business intelligence analyst, a business executive, a finance manager, an FP&A analyst, an investment banker, or an entrepreneur365 Careers’ courses are the perfect place to start.\xa0\n",
    'User_Id': 432
},
{
    'Description': "Bundling the courses and know how of successful instructors, Academind strives to deliver high quality online education.\xa0\nOnline Education, Real-Life Success - that's what Academind stands for. Learn topics like web development, data analyses and more in a fun and engaging way.\nCurrently, you can find courses published by Maximilian Schwarzmüller and Manuel Lorenz, more instructors to come!\nKeep learning!",
    'User_Id': 480
},
{
    'Description': 'I have written and published a number of books that are available on Amazon, including best selling books on Wordpress ("Wordpress for Beginners 2020") and search engine optimization ("SEO 2020"). \xa0I also\xa0run a website called ezSEONews, where I teach my visitors and newsletter subscribers a number of skills required for running a successful website.\xa0 \xa0 \xa0 \xa0 \xa0As an ex-schoolteacher, I hope I can make complicated topics simple to understand.\xa0 I certainly enjoy trying!\xa0 ',
    'User_Id': 529
},
{
    'Description': "Hi, I'm Brad and I’ve taught web development to countless coworkers and held training sessions for fortune 100 companies.I also teach local night classes and run a somewhat popular YouTube channel named LearnWebCode.\n I’m a front-end developer, designer, and educator. I’ve been building user interfaces for over a decade for the world's largest brands, international technology leaders, and national political campaigns. \n I'm fortunate to enjoy the development work I do, but my true passion is helping people learn.",
    'User_Id': 542
},
{
    'Description': "Hey, I'm\xa0Caleb Jost. I'm an award-winning web designer in Austin,\xa0TX. I run a six-figure digital studio and have taught digital marketing at the university level. I am passionate about empowering entrepreneurs and small business owners to build prosperous businesses through compelling web design and digital marketing. I'm from a family of small business owners, so I'm well aware of the unique challenges SMBs face.I've worked in tech for startups, Fortune 100 companies, and as a self-employed business owner. I'm a Wix Legend Partner and am certified in Google Ads, Inbound Marketing, and SEO. In my free time, I like to play music (bass, guitar, ukulele, and keyboard), read, hike, spend time with friends and family, explore new skills and hobbies, learn languages (German, Portuguese, and Spanish), and travel internationally. ",
    'User_Id': 567
},
{
    'Description': 'Joe Natoli has launched five successful online courses with Udemy on the topics of User Experience (UX) and User Interface (UI) Design, with more than 200,000+ students enrolled to date. Joe has been preaching and practicing the gospel of User Experience (UX) to Fortune 100, 500 and Government organizations for nearly three decades. That work includes commercial industry leaders like Google Ventures, Kroll/Duff + Phelps, Broadridge, Conde Nast, Johns Hopkins, Mettler-Toledo, PHH Arval, SC Johnson and Wolters Kluwer, as well as government agencies like the National Science Foundation, National Institutes of Health and the Dept. of Homeland Security. Joe devotes half of his practice to writing, coaching, and speaking. From guiding students at the beginning of their careers to integrating UX into the work of seasoned veteran developers and designers, he is immensely passionate about the inherent power of UX and design. The remaining half of Joe’s practice is dedicated to training Enterprise Design and Development teams, helping them integrate best practices in UX into their product development efforts. In addition, he does a limited number of UX Audit engagements to help organizations identify and overcome UX-related obstacles to product adoption.Joe has been speaking publicly on the topics of User Experience (UX) and Design across the globe for 24 years, from global conferences like HOW Design Live, SDD, DevWeek, and IxDA South America. He also makes it a point to spend time talking to students across the country at colleges and universities, in an effort to give back what others have so generously given him. His latest book on UX Strategy and Product Improvement, Think First, was published worldwide on October 5, 2015.In addition, he has written numerous articles about the roles Design and UX play in business success for publications such as Fast Company, SmartCEO, The AIGA Journal, The Baltimore Business Journal and Business Monthly. His articles, advice and videos can be seen at his website, as well as across various social media platforms.',
    'User_Id': 575
},
{
    'Description': 'Hello everyone! I am an artist that focuses on\xa0digital painting and character design. I want to encourage my students on creativity and have an eye for design. My main goal as an instructor is to give inspiration for beginner artists and help them by giving a simpler way of viewing drawing and for them to have fun with art!',
    'User_Id': 588
},
{
    'Description': 'At the age of 17 I began a 6th month internship with an animation studio out of Utah. After my internship was up, I was hired on to build backgrounds and to design props and characters for animation projects. I then began to do my own freelance work on the side through networking and using online freelancing sites. Now I work as a freelance Illustrator and designer working on my own time from where ever I want. ',
    'User_Id': 600
},
{
    'Description': 'If anyone has questions about which course may work best for them, please feel free to contact or message me. I have had many self-made titles over the years: Brand Manager, Digital Architect, Interactive Designer, Graphic Designer, Web Developer and Social Media Expert, to name a few. My name is Lindsay Marsh and I have been creating brand experiences for my clients for over 15\xa0years. As a freelance graphic designer, I have worked on a wide variety of projects both in the digital and print space.\xa0I have had the wonderful opportunity of taking classes at some of the top design schools in the world: Parsons at The New School, The Pratt Institute and NYU.\xa0I have had the pleasure of teaching over 300,000+ students globally online. I have provided private tutoring in the the area of design and marketing for over 8 years. I am also now a certified Canva Certified Creative. \xa0The thing I enjoy most of all about being a teacher is seeing my students flourish and to be able to start careers that are passionate and rewarding.\xa0I have a Facebook group dedicated to helping my students thrive and start new freelance design businesses. I want to get to know my students and provide additional challenges that get them ready for wonderful opportunities in the design world. ',
    'User_Id': 613
},
{
    'Description': "Sharing is who I am, and teaching is where I am at my best, because I've been on both sides of that equation, and getting to deliver useful training is my meaningful way to be a part of the creative community.I've spent a long time watching others learn, and teach, to refine how I work with you to be efficient, useful and, most importantly, memorable. I want you to carry what I've shown you into a bright future.I have a wife (a lovely Irish girl) and kids. I have lived and worked in many places (as Kiwis tend to do) – but most of my 14+ years of creating and teaching has had one overriding theme: bringing others along for the ride as we all try to change the world with our stories, our labours of love and our art.I'm a certified Adobe instructor (ACI) in Ireland. I'm also an Adobe Certified Expert (ACE) and have completed the Adobe Certified Associate training (ACA). And I don't just do Adobe. Remember, media is a very broad term – digital blew out the borders, so we are all constantly learning.I've been teaching for 14+ years. I come from being a media designer and content creator – so I understand exactly where you're at now. I've been there. I love this stuff. Print, digital publishing, web and video. I can see how it all connects. And I can see how we can share those connections.I built Bring Your Own Laptop in Ireland, New Zealand, Australia & online. I have a great team working with me to keep BYOL at the top of Adobe and digital media training. I understand business, I have one – so I know how important it is to get it right and make it work for you.Now my focus is on Udemy. It's my mission to bring you the best training for digital media on Udemy.Daniel Walter Scott",
    'User_Id': 626
},
{
    'Description': "Derrick is a lifelong learner with a passion for making bland things beautiful.He has spent his entire career in the creative arts and marketing sector. He had the opportunity to work with brands such as MTV, Nintendo, and Netflix while employed as an intern for Seven 2 Interactive, which definitely set the trajectory for his design career. in 2008, he and his wife opened a small graphic design and marketing agency in Montana - they spent the next decade creating websites, logos, and more for clients all over the world. Derrick has been the creative director for major international brands and recently made a career pivot to include online teaching. He loves helping students realize their full potential while turning their interests and passions into strong skillsets and careers. From hand-illustrating logos to creating websites for global brands, Derrick knows what it takes to succeed as a graphic designer, a freelancer, and a business owner.He is passionate about helping others find success doing what they love and he currently teaches over 130,000 students online on several different platforms. From Photoshop to Illustrator to InDesign - if it revolves around graphic design,\xa0Derrick is excited about teaching it to others.Derrick lives in Montana with his wife, his four daughters, his son, and the family's two dogs. When he has a free moment, he enjoys paddleboarding, mountain biking, and snowboarding. In his spare time, he also enjoys making GoPro videos with his kids and finding ways to continue to evolve his craft as a designer and artist.",
    'User_Id': 639
},
{
    'Description': 'Hi, and thanks for checking out my course !Currently, I’m the founder of IQ x EQ, an advisory and training agency focused on strategy, innovation and service design. I am advising firms on their business and human transformation projects and the innovation of their business models and service offerings.I built my expertise thanks to 20 years of work experience with large financial institutions across Europe and Asia in operations, relationship management, product, innovation, strategy and M&A.This well-rounded professional experience has provided me with business acumen and a thorough understanding of business fundamentals.I provide mentorship to startup founders and I’m a member of a network of 100+ entrepreneurs, angel investors and consultants who support promising early-stage, post-revenue startups through funding, mentoring and networking.I am on Udemy because I love learning, and I love sharing my learnings and experience.',
    'User_Id': 652
},
{
    'Description': "3 parts design nerd, 4 parts passionate educator, 2 parts biker extraordinaireLaura is a Learning Experience Designer at Lyft and an Ideo U teaching team lead. In past lives, she's been a User Experience Designer at SAP, taught at the Stanford d.school, and has conducted hundreds of design thinking workshops.When she's not teaching people about using game mechanics for learning or interview techniques for empathy work, Laura can be found competing in triathlons, riding hundreds of miles on her bike for fun, or hunting for the best gluten-free bakeries around.",
    'User_Id': 665
},
{
    'Description': "It's been 10 years since I started working in elearning. I understand the limitations and the possibilities of online teaching. I'm excited for the future and I'm amazed at what we can do right now.It's been 15 years since I first taught a class. I spent three years teaching english in Seoul. I loved seeing the progress of my students and I loved knowing they were having a good time in my class. I learnt about how to write a solid lesson plan the only way I believe anyone can... by seeing the results right there in front of me.It's been 20 years since I first designed and built a website. I remember learning dreaweaver and flash while I was a student and been hooked on the power it gives us, even then I didn't know how far it would go. I've dedicated my life to building and designing web apps to the highest standard and now I want to pass that on. It's been 35 years since I started school. and I wasn't that good at school truth be told. I had dyslexia and couldn't keep up, having overcome that and managed to find ways to teach myself the skills I need to get some fantastic jobs I'm confident I can explain things in a way everyone can understand and, knowing how much I struggled to learn, I can be very patient in explaining how things need to be done. I believe all the skills I have built over the years all add up to making great online course to help you move forward with your goals and I look forward to working with you on them",
    'User_Id': 676
},
{
    'Description': 'Biochemistry scientist, Chemical and Process EngineerSenior Process Engineer at LG\xa0ChemResearch Experience: Karolinska Institutet, KFU Graz, Polish Academy of Sciences\xa0 and more..I am an open-minded, curious and eager person who is always ready to experience something new. I am more of an analytical person so I alway enjoy solving different types of problems.Area of freelance work:- Product development from formulation to manufacturing process,- Process optimisation, plan of synthesis,- Chemistry problem solver (biochemistry and cosmetic chemistry)- Food safety expert (proven by certificate)- Chemistry method design- I have finished design thinking course (Luzerne Switzerland) I like creative work.',
    'User_Id': 689
},
{
    'Description': 'Leena is a Dalai Lama Fellow, a Fulbright scholarship recipient, a Wall Street Journal “Woman of Note,” and was awarded a Global Impact Innovator by Expo Live | Expo 2020 Dubai. She is Executive Chairperson of 3BL Associates (3BL), a people+planet strategy consultancy working on interconnected sustainable development issues. Leena has advised Nobel Peace Prize nominees, multinational corporations, international governments, and multilaterals on inclusive and financially sustainable models to advance social and environmental progress. Through 3BL’s think-do-tank, Leena has cofounded award-winning ventures like Public-Planet Partnerships, Diversity On Board, and Nonviolent Resilience. Leena is also the author of Compassionate Counterterrorism: The Power of Inclusion in Fighting Fundamentalism, and was an impact advisor to the London-based investment firm Future Planet Capital. She has served on numerous boards and as a judge and mentor for entrepreneurship competitions like MIT’s Innovate for Refugees.Leena holds a BS in Culture and Interpersonal Communications from New York University, an MA in Globalization Studies from Dartmouth College, and is an alumna of Harvard Business School’s Executive Education Program, the THNK School for Creative Leadership in Amsterdam, and Singularity University.',
    'User_Id': 702
}]