module.exports = [
  { Course_Id: 1, Name: "Course Introduction" },
  { Course_Id: 1, Name: "The 25+ Guidelines Of Amazing Web Design" },
  { Course_Id: 1, Name: "Course Summary" },
  { Course_Id: 1, Name: "Conclusion" },
  { Course_Id: 2, Name: "Introduction" },
  { Course_Id: 2, Name: "Basic Syntax" },
  { Course_Id: 2, Name: "Comparison & Conditional Execution" },
  { Course_Id: 2, Name: "DOM Manipulation" },
  { Course_Id: 2, Name: "Final Overview" },
  { Course_Id: 3, Name: "Q&A Section Project" },
  { Course_Id: 3, Name: "Tabs Project" },
  { Course_Id: 4, Name: "Introduction and Installations" },
  { Course_Id: 4, Name: "Background video project" },
  { Course_Id: 4, Name: "Counter Project" },
  { Course_Id: 5, Name: "Introduction" },
  { Course_Id: 5, Name: "PHP Basics" },
  { Course_Id: 5, Name: "PHP Arrays" },
  { Course_Id: 5, Name: "PHP If, Else & Elseif" },
  { Course_Id: 5, Name: "PHP Operators" },
  { Course_Id: 5, Name: "PHP Loops" },
  { Course_Id: 5, Name: "PHP Functions" },
  { Course_Id: 5, Name: "Coding a Dynamic PHP Restaurant Website" },
  { Course_Id: 6, Name: "Introduction" },
  { Course_Id: 6, Name: "Getting started with coding" },
  {
    Course_Id: 6,

    Name: "Bonus material from the other R-Tutorials courses",
  },
  { Course_Id: 7, Name: "Introduction" },
  { Course_Id: 7, Name: "Getting setup with Tools" },
  {
    Course_Id: 7,

    Name: "Getting Deeper into Machine learning frameworks and algorithms",
  },
  { Course_Id: 8, Name: "Introduction" },
  { Course_Id: 8, Name: "Pandas" },
  { Course_Id: 8, Name: "NumPy" },
  { Course_Id: 8, Name: "SciKit-Learn" },
  { Course_Id: 8, Name: "matplotlib" },
  { Course_Id: 8, Name: "NLTK" },
  { Course_Id: 9, Name: "Getting Started" },
  { Course_Id: 9, Name: "Working with ggplot" },
  { Course_Id: 9, Name: "Sampling from populations" },
  { Course_Id: 9, Name: "Simple Linear Regression in R" },
  {
    Course_Id: 10,

    Name: "Introduction to Artificial Intelligence",
  },
  {
    Course_Id: 10,

    Name: "Road Map for AI and Machine Learning (ML)",
  },
  { Course_Id: 10, Name: "Introduction to Machine Learning" },
  { Course_Id: 10, Name: "Types of Machine Learning" },
  { Course_Id: 11, Name: "Introduction and setup" },
  {
    Course_Id: 11,

    Name: "Creating a basic Android App in 15 minutes",
  },
  {
    Course_Id: 11,

    Name: "Bonus app features (Complete in 11 minutes)",
  },
  { Course_Id: 12, Name: "Introduction To Flutter" },
  { Course_Id: 12, Name: "Flutter States" },
  { Course_Id: 12, Name: "layouts" },
  { Course_Id: 12, Name: "AppBar & TabBar Widget" },
  { Course_Id: 12, Name: "Custom Widgets" },
  { Course_Id: 12, Name: "Input & Selections Widgets" },
  { Course_Id: 12, Name: "Drawer Widget & Routes" },
  { Course_Id: 12, Name: "Notification Widgets" },
  {
    Course_Id: 13,

    Name: "Hey there ! Let me introduce you to Android and Android Studio !",
  },
  { Course_Id: 13, Name: "Android Versions" },
  { Course_Id: 14, Name: "Introduction" },
  { Course_Id: 14, Name: "Setup" },
  { Course_Id: 14, Name: "Basic Swift 3" },
  {
    Course_Id: 14,

    Name: "Your First iOS 10 App - An Astronomy Screen Torch!",
  },
  { Course_Id: 14, Name: "App 2 - Temperature Converter" },
  { Course_Id: 14, Name: "App 3 - Calculator" },
  { Course_Id: 14, Name: "App 4 - Back to the Future" },
  { Course_Id: 14, Name: "App 5 - Where was I? - GPS and Maps" },
  { Course_Id: 14, Name: "Great App Design" },
  { Course_Id: 14, Name: "App 6 - Quick Share (Photos)" },
  { Course_Id: 15, Name: "Getting Started" },
  { Course_Id: 15, Name: "Your First App" },
  { Course_Id: 15, Name: "Learning To Code" },
  { Course_Id: 15, Name: "Creating A Tip Calculator App" },
  { Course_Id: 15, Name: "Creating A Food Journal App" },
  { Course_Id: 15, Name: "Expanding Our Food Journal App" },
  {
    Course_Id: 15,

    Name: "Adding Geo-Location And Maps to Our Food Journal App",
  },
  { Course_Id: 15, Name: "Creating A Multi-Touch Photo-based App" },
  { Course_Id: 15, Name: "Submitting To The App Store" },
  { Course_Id: 16, Name: "Introduction" },
  { Course_Id: 16, Name: "The 5 Main Steps" },
  { Course_Id: 16, Name: "Web Hosting and Domain Name" },
  { Course_Id: 16, Name: "Installing WordPress and Logging In" },
  { Course_Id: 16, Name: "Deleting Demo Content" },
  { Course_Id: 16, Name: "Changing Our Theme" },
  { Course_Id: 16, Name: "Customizing Our Theme" },
  { Course_Id: 16, Name: "Adding Pages" },
  { Course_Id: 16, Name: "Adding Blog Posts" },
  { Course_Id: 16, Name: "Changing Our Fonts" },
  { Course_Id: 17, Name: "Introduction" },
  { Course_Id: 17, Name: "The Domain Name" },
  { Course_Id: 17, Name: "Web Hosting" },
  { Course_Id: 17, Name: "Getting your Website Live" },
  { Course_Id: 18, Name: "Hello and Welcome!" },
  { Course_Id: 18, Name: "User Interface" },
  { Course_Id: 18, Name: "Working with tools and layers" },
  { Course_Id: 18, Name: "Creating Shapes" },
  { Course_Id: 18, Name: "Working With Layers & Groups" },
  { Course_Id: 18, Name: "Moving and Resizing" },
  { Course_Id: 18, Name: "Zooming and Panning" },
  { Course_Id: 18, Name: "Blend Modes and Adding Effects" },
  { Course_Id: 18, Name: "Inserting Text" },
  { Course_Id: 18, Name: "Design in Photoshop" },
  { Course_Id: 19, Name: "Course Overview" },
  { Course_Id: 19, Name: "Getting Started With WordPress" },
  {
    Course_Id: 19,

    Name: "Customizing Your Website & Adding New Features",
  },
  {
    Course_Id: 19,

    Name: "The Big Reveal & Your Site Post Launch",
  },
  { Course_Id: 20, Name: "Introduction" },
  { Course_Id: 20, Name: "HTML" },
  { Course_Id: 20, Name: "CSS" },
  { Course_Id: 20, Name: "Bringing it all together" },
  { Course_Id: 21, Name: "INTRODUCTION" },
  {
    Course_Id: 21,

    Name: "Professional Logo Design- Abobe Illustrator",
  },
  { Course_Id: 22, Name: "Welcome" },
  { Course_Id: 22, Name: "Basic Operations" },
  { Course_Id: 22, Name: "Course Recap" },
  { Course_Id: 23, Name: "Introduction" },
  { Course_Id: 23, Name: "Habits of Successful Artists" },
  { Course_Id: 23, Name: "Art Basics" },
  { Course_Id: 23, Name: "Art Project" },
  { Course_Id: 23, Name: "Course Recap" },
  {
    Course_Id: 24,

    Name: "Step-by-Step Instruction Using the Reilly Technique",
  },
  {
    Course_Id: 24,

    Name: "Demonstrations Using the Reilly Technique",
  },
  {
    Course_Id: 25,

    Name: "Introduction to logo design fundamentals",
  },
  { Course_Id: 25, Name: "Fonts for Logo" },
  { Course_Id: 25, Name: "Vector Elements and building vectors" },
  { Course_Id: 25, Name: "Constructing the Logo" },
  {
    Course_Id: 25,

    Name: "Black and White | Horizontal Vs. Vertical",
  },
  { Course_Id: 25, Name: "Finishing touches on the Logo" },
  { Course_Id: 25, Name: "Bonus Features" },
  {
    Course_Id: 26,

    Name: "Analysis of Everyday Things Introduction",
  },
  {
    Course_Id: 26,

    Name: "Analysis of Modern Perpetuations of Old Designs.",
  },
  {
    Course_Id: 26,

    Name: "Analysis of Everyday Things Conclusion",
  },
  { Course_Id: 27, Name: "I’m not creative… What do I do now?" },
  { Course_Id: 27, Name: "Create + Activity = Creativity" },
  { Course_Id: 27, Name: "Stages of the Creative Process" },
  { Course_Id: 27, Name: "Identification Phase + 5 Tools" },
  { Course_Id: 27, Name: "Preparation Phase + 4 Tools" },
  { Course_Id: 27, Name: "Incubation Phase + 2 Tips" },
  { Course_Id: 27, Name: "Warming Up Phase + 6 Tools" },
  { Course_Id: 27, Name: "Enlightenment Phase + 4 Tools" },
  { Course_Id: 27, Name: "Elaboration Phase + 5 Tools" },
  { Course_Id: 27, Name: "Verification Stage + 5 Tools" },
  { Course_Id: 28, Name: "Introduction to Knuckle joint" },
  { Course_Id: 28, Name: "Design of knuckle joint" },
  { Course_Id: 29, Name: "Introduction" },
  {
    Course_Id: 30,
    Name: "デジタルトランスフォーメーション(DX)とサービスデザイン",
  },
];
